# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LanguagePlatform' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LanguagePlatform
	pod 'Alamofire', '4.4.0'
	pod 'SwiftyJSON', '3.1.4'
	pod 'SQLite.swift', '0.11.2'
    pod 'SnapKit',  '3.2.0'

  

end
